/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FriendsAddRouteImport } from './routes/friends.add'
import { Route as ChatFriendIdRouteImport } from './routes/chat.$friendId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsAddRoute = FriendsAddRouteImport.update({
  id: '/friends/add',
  path: '/friends/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatFriendIdRoute = ChatFriendIdRouteImport.update({
  id: '/chat/$friendId',
  path: '/chat/$friendId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/chat/$friendId': typeof ChatFriendIdRoute
  '/friends/add': typeof FriendsAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/chat/$friendId': typeof ChatFriendIdRoute
  '/friends/add': typeof FriendsAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/chat/$friendId': typeof ChatFriendIdRoute
  '/friends/add': typeof FriendsAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/chat/$friendId' | '/friends/add'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/chat/$friendId' | '/friends/add'
  id: '__root__' | '/' | '/settings' | '/chat/$friendId' | '/friends/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ChatFriendIdRoute: typeof ChatFriendIdRoute
  FriendsAddRoute: typeof FriendsAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/add': {
      id: '/friends/add'
      path: '/friends/add'
      fullPath: '/friends/add'
      preLoaderRoute: typeof FriendsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$friendId': {
      id: '/chat/$friendId'
      path: '/chat/$friendId'
      fullPath: '/chat/$friendId'
      preLoaderRoute: typeof ChatFriendIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ChatFriendIdRoute: ChatFriendIdRoute,
  FriendsAddRoute: FriendsAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
