/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunitiesIndexRouteImport } from './routes/communities.index'
import { Route as FriendsAddRouteImport } from './routes/friends.add'
import { Route as CommunitiesCommunityIdRouteImport } from './routes/communities.$communityId'
import { Route as ChatFriendIdRouteImport } from './routes/chat.$friendId'
import { Route as AppsConnectRouteImport } from './routes/apps.connect'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsAddRoute = FriendsAddRouteImport.update({
  id: '/friends/add',
  path: '/friends/add',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesCommunityIdRoute = CommunitiesCommunityIdRouteImport.update({
  id: '/communities/$communityId',
  path: '/communities/$communityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatFriendIdRoute = ChatFriendIdRouteImport.update({
  id: '/chat/$friendId',
  path: '/chat/$friendId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsConnectRoute = AppsConnectRouteImport.update({
  id: '/apps/connect',
  path: '/apps/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/settings': typeof SettingsRoute
  '/apps/connect': typeof AppsConnectRoute
  '/chat/$friendId': typeof ChatFriendIdRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/friends/add': typeof FriendsAddRoute
  '/communities/': typeof CommunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/settings': typeof SettingsRoute
  '/apps/connect': typeof AppsConnectRoute
  '/chat/$friendId': typeof ChatFriendIdRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/friends/add': typeof FriendsAddRoute
  '/communities': typeof CommunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/settings': typeof SettingsRoute
  '/apps/connect': typeof AppsConnectRoute
  '/chat/$friendId': typeof ChatFriendIdRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/friends/add': typeof FriendsAddRoute
  '/communities/': typeof CommunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authorize'
    | '/settings'
    | '/apps/connect'
    | '/chat/$friendId'
    | '/communities/$communityId'
    | '/friends/add'
    | '/communities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authorize'
    | '/settings'
    | '/apps/connect'
    | '/chat/$friendId'
    | '/communities/$communityId'
    | '/friends/add'
    | '/communities'
  id:
    | '__root__'
    | '/'
    | '/authorize'
    | '/settings'
    | '/apps/connect'
    | '/chat/$friendId'
    | '/communities/$communityId'
    | '/friends/add'
    | '/communities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizeRoute: typeof AuthorizeRoute
  SettingsRoute: typeof SettingsRoute
  AppsConnectRoute: typeof AppsConnectRoute
  ChatFriendIdRoute: typeof ChatFriendIdRoute
  CommunitiesCommunityIdRoute: typeof CommunitiesCommunityIdRoute
  FriendsAddRoute: typeof FriendsAddRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/add': {
      id: '/friends/add'
      path: '/friends/add'
      fullPath: '/friends/add'
      preLoaderRoute: typeof FriendsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$communityId': {
      id: '/communities/$communityId'
      path: '/communities/$communityId'
      fullPath: '/communities/$communityId'
      preLoaderRoute: typeof CommunitiesCommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$friendId': {
      id: '/chat/$friendId'
      path: '/chat/$friendId'
      fullPath: '/chat/$friendId'
      preLoaderRoute: typeof ChatFriendIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/connect': {
      id: '/apps/connect'
      path: '/apps/connect'
      fullPath: '/apps/connect'
      preLoaderRoute: typeof AppsConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizeRoute: AuthorizeRoute,
  SettingsRoute: SettingsRoute,
  AppsConnectRoute: AppsConnectRoute,
  ChatFriendIdRoute: ChatFriendIdRoute,
  CommunitiesCommunityIdRoute: CommunitiesCommunityIdRoute,
  FriendsAddRoute: FriendsAddRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
